export const FETCH_RECIPES = "FETCH_RECIPES"
export const FETCH_USER = "FETCH_USER"

export const ADD_RECIPE_INGREDIENT = "ADD_RECIPE_INGREDIENT"
export const REMOVE_RECIPE_INGREDIENT = "REMOVE_RECIPE_INGREDIENT"
export const UPDATE_RECIPE_INGREDIENT = "UPDATE_RECIPE_INGREDIENT"
